# Generated by Django 2.0.5 on 2018-05-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensorTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('altitude', models.FloatField(null=True)),
                ('_long', models.FloatField(null=True)),
                ('sensor1', models.IntegerField()),
                ('sensor2', models.IntegerField()),
                ('sensor3', models.IntegerField()),
                ('sensor4', models.IntegerField()),
                ('tag', models.IntegerField()),
                ('lat', models.FloatField(null=True)),
            ],
        ),
    ]
