# Generated by Django 2.0.5 on 2018-05-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensortag',
            old_name='_id',
            new_name='tag_id',
        ),
        migrations.RenameField(
            model_name='sensortag',
            old_name='_long',
            new_name='var_long',
        ),
    ]
